### ISSUE TITLE
On a besoin de plusieurs workers à la fois

### ISSUE THREAD

**Issue by czj** [levups/http-tester#2]
Si je ne me trompe pas, Rackup ne permet pas de servir plus d'une requête à la fois. Donc si on tape une requête "timeout 30s" on va bloquer l'app 30s et donc être bien embêtés ...

Comme c'est une app légère on pourrait avoir 5 workers, ou même 10 workers web dans un petit dyno.

**Comment by bobmaerten** [comment]
Yep c'était vraiment histoire de pousser l'app dans son état existant en ajoutant des tests.

**Comment by czj** [comment]
Ce qui est cool :)
